name = "template/multi_place"
version = "0.1.0"
authors = ["c0balt60"]
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
Charm = { wally = "littensy/charm", version = "^0.10.0" }
CharmSync = { wally = "littensy/charm-sync", version = "^0.3.0" }
ReactCharm = { wally = "littensy/react-charm", version = "^0.3.0" }
Sift = { wally = "csqrl/sift", version = "^0.0.11" }
Immut = { wally = "solarhorizon/immut", version = "^0.4.4" }
React = { wally = "haedrix/react", version = "^17.3.7" }
react_roblox = { wally = "haedrix/react-roblox", version = "^17.3.7" }
# react_devtools_core = { wally = "haedrix/react-devtools-core", version = "17.3.7" }
# react_globals = { wally = "haedrix/react-globals", version = "17.3.7" }
react_spring = { wally = "chriscerie/react-spring", version = "^2.0.0" }
Promise = { wally = "lukadev-0/typed-promise", version = "^4.0.2" }
Cmdr = { wally = "evaera/cmdr", version = "^1.12.0" }
Janitor = { wally = "1foreverhd/janitor", version = "^1.18.15" }
Topbarplus = { name = "dancodesrbx/topbarplus", version = "^3.0.2" }
Fastcast = { wally = "megamonsta2/fastcast", version = "^1.0.0" }
Signal = { wally = "data-oriented-house/lemonsignal", version = "^1.11.0" }
Bootstrapper = { wally = "ldgerrits/bootstrapper", version = "^1.2.1" }
DocumentService = { wally = "anthony0br/documentservice", version = "^1.2.2" }
t = { wally = "osyrisrblx/t", version = "^3.1.1" }

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"
sync = ".lune/sync.luau"
reload = ".lune/reload.luau"
prepare = ".lune/prepare.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }
pathfs = { name = "jiwonz/pathfs", version = "0.6.0", target = "lune" }
argparse = { name = "caveful_games/argparse", version = "0.1.2", target = "lune" }
darklua = { name = "pesde/darklua", version = "^0.17.2", target = "lune" }
UILabs = { name = "pepeeltoro41/ui_labs", version = "^2.4.2" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[overrides]
# React overrides
"CharmSync>React" = { name = "haedrix/react", version = "17.3.7" }
"react_reflex>React" = "React"
"react_spring>React" = "React"
"react_spring>ReactRoblox" = "react_roblox"
"react_is>React" = "React"
"react_error_boundary>React" = "React"
"react_error_boundary>ReactRoblox" = "react_roblox"
# roact_compat overrides
# "roact_compat>React" = "react"
# "roact_compat>react-roblox" = "react_roblox"
# "roact_compat>react-reconciler" = "react_reconciler"
# "roact_compat>scheduler" = "scheduler"
# "roact_compat>shared" = "shared"
# charm overrides
"Charm>React" = "React"
"Charm>ReactRoblox" = "react_roblox"
# charm_sync overrides
"CharmSync>ReactRoblox" = "react_roblox"
# ripple overrides
"ripple>React" = "React"
"ripple>ReactRoblox" = "react_roblox"

[patches]
"wally#littensy/react-charm" = { "0.3.0 roblox" = "patches/wally#littensy+react-charm-0.3.0+roblox.patch" }
# "wally#haedrix/react" = { "17.3.7 roblox" = "patches/wally#haedrix+react-17.3.7+roblox_rc_deviations.patch" }
# "wally#haedrix/scheduler" = { "17.3.7 roblox" = "patches/wally#haedrix+scheduler-17.3.7+roblox_error_bug.patch" }
# "wally#yetanotherclown/planck-runservice" = { "0.2.0 roblox" = "patches/wally#yetanotherclown+planck-runservice-0.2.0+roblox_server_performance_bug_hack.patch" }
# "wally#ukendio/jecs" = { "0.9.0 roblox" = "patches/wally#ukendio+jecs-0.9.0+roblox_latest_commit.patch" }
# "wally#pepeeltoro41/jecs-utils" = { "1.4.0 roblox" = "patches/wally#pepeeltoro41+jecs-utils-1.4.0+roblox.patch" }
# "wally#haedrix/react-globals" = { "17.3.7 roblox" = "patches/wally#haedrix+react-globals-17.3.7+roblox_rc_react_globals.patch" }
# "wally#chriscerie/react-spring" = { "2.0.0 roblox" = "patches/wally#chriscerie+react-spring-2.0.0+roblox_use_haedrix_shared_types.patch" }
# "wally#yetanotherclown/planck" = { "0.2.0 roblox" = "patches/wally#yetanotherclown+planck-0.2.0+roblox.patch" }
# "wally#haedrix/react-reconciler" = { "17.3.7 roblox" = "patches/wally#haedrix+react-reconciler-17.3.7+roblox.patch" }
